### ISSUE TITLE
Can't resolve '@ant-design/compatible/assets/index.css

### ISSUE THREAD

**Issue by yi-ren-brokerbay** [ant-design/codemod-v4#101]
Can't resolve '@ant-design/compatible/assets/index.css

```
It's recommended to install or upgrade these dependencies to ensure working well with antd4

* Update antd^4.0.0 in dependencies
* Install @ant-design/compatible^1.0.0 
* Update @ant-design/icons^4.0.0 in dependencies

----------- Thanks for using @ant-design/codemod 1.0.2 -----------
```
Then
```
yarn add @ant-design/compatible
```
successfully
Can't resolve '@ant-design/compatible/assets/index.css in 

Thank you for your help

**Comment by vagusX** [comment]
@yi-ren-brokerbay maybe you need a css-loader in your webpack config? It seems like a webpack problem. And the info you provide is not enough at the same time. More details please.
I see that the css file is existed in unpkg https://unpkg.com/browse/@ant-design/compatible@1.0.0/assets/index.css

**Comment by yi-ren-brokerbay** [comment]
@vagusX  Thank you for your reply, I could not figure out why and I ended up migrating all the forms and get rid of the compatible package :)
