### ISSUE TITLE
you must commit or stash them firstly

### ISSUE THREAD

**Issue by guchengjie** [ant-design/codemod-v4#110]
当前项目用的代码版本管理用的是svn，为什么怎么运行都提示
Sorry that there are still some git changes
 you must commit or stash them firstly

**Comment by vagusX** [comment]
你可以搜索 issue 列表解决你的问题

* https://github.com/ant-design/codemod-v4/issues/80
* https://github.com/ant-design/codemod-v4/issues/44

`antd4-codemod $your_dir --force` 加一个 --force 选项来跳过 git 操作，但是还是一个危险操作，请先保障本地代码已提交，工作区无变更内容
