### ISSUE TITLE
Select Option tag ， 自定义属性options报错

### ISSUE THREAD

**Issue by wjing0904** [ant-design/codemod-v4#111]
"antd": "^4.0.3",
  "react": "^16.13.0",
   "react-dom": "^16.13.0",

Error：
index.js:1 The above error occurred in the <ForwardRef(Select)> component:
    in ForwardRef(Select) (created by Select)

**Comment by vagusX** [comment]
@wjing0904  Please report an issue to [ant design main repo](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
