### ISSUE TITLE
关于Form表单必填项的无红色星的bug

### ISSUE THREAD

**Issue by gebilaoman** [ant-design/codemod-v4#118]
现象：antd升级到4.0.0之后，Form表单中必填项的红色星星不见了

初步解决：如果在该类引入“import "antd/lib/form/style/index.less”或者“import "antd/dist/antd.css";”的话，就没有问题。

我理解的是，不应该引入任何css才对，麻烦看一下

[demo](https://codesandbox.io/s/xenodochial-neumann-b5g44?file=/src/index.js)

![image](https://user-images.githubusercontent.com/26354664/78650537-a346d080-78f1-11ea-93d3-ec266c1092a8.png)

![image](https://user-images.githubusercontent.com/26354664/78650726-e1dc8b00-78f1-11ea-9b3c-d1846159d95b.png)

**Comment by vagusX** [comment]
Please report an issue to [ant design main repo](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by ycshill** [comment]
出现了同样的问题
