### ISSUE TITLE
npx -p @ant-design/codemod-v4 antd4-codemod src ERROR

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/codemod-v4#136]
Sorry that there are still some git changes

 you must commit or stash them firstly

**Comment by afc163** [comment]
Just follow the instruction, commit or stash your changes.

**Comment by aiyudeleng** [comment]
> Just follow the instruction, commit or stash your changes.

how?

**Comment by aiyudeleng** [comment]
> Just follow the instruction, commit or stash your changes.

我的项目部署在本地，没有上传到git

**Comment by afc163** [comment]
#80

**Comment by aiyudeleng** [comment]
> #80

thank you
