### ISSUE TITLE
'@ant-design/icons' does not contain an export named 'UploadOutlined'.

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/codemod-v4#137]
通过antd4-codemod src --force升级后，显示检查通过
![image](https://user-images.githubusercontent.com/31436484/82532415-ea241900-9b73-11ea-9ca8-3e93f4141deb.png)

但是运行后报错
'@ant-design/icons' does not contain an export named 'UploadOutlined'.

类似的Icon还有很多

**Comment by aiyudeleng** [comment]
安装@ant-design/icons后解决

**Comment by josh231101** [comment]
Just to be clear and make a logical answer.
Ant design from version 3 to 4, did one of the major changes,removing icons from antd and created a separate dependency
Just install this via npm or yarn 
```
 yarn add @ant-design/icons
```
Sadly you will have to refactor your components to the correct icon component, so check this page :+1: 
https://ant.design/components/icon/
