### ISSUE TITLE
Cannot read property 'numerator' of undefined   升级到4.+版本后，编译less报错

### ISSUE THREAD

**Issue by Mh2336393** [ant-design/codemod-v4#196]
![image](https://user-images.githubusercontent.com/48132028/98539574-8af3c580-22c7-11eb-9c5c-929a801934e5.png)
![image](https://user-images.githubusercontent.com/48132028/98539627-a3fc7680-22c7-11eb-808a-f9a790412bf5.png)
![image](https://user-images.githubusercontent.com/48132028/98539746-cee6ca80-22c7-11eb-8398-3eb0a927a26d.png)
我别人相同的问题。也没有解决啊

**Comment by yaocoding007** [comment]
@Mh2336393 有解决这个问题吗
