### ISSUE TITLE
Error evaluating function `fade`: Argument cannot be evaluated to a color

### ISSUE THREAD

**Issue by ywcr** [ant-design/codemod-v4#199]
引入 @import '~antd/dist/antd.less'; 

Module build failed:

      &-active {
        background: fade(@calendar-item-active-bg, 20%);
                  ^
Error evaluating function `fade`: Argument cannot be evaluated to a color
      in /Users/yao/yaowei/project/ucenter-frontend/node_modules/antd/lib/date-picker/style/panel.less (line 623, column 20)

直接引入 css 或者再 js中引入 不会报错，但是themes覆盖好像没生效

**Comment by ywcr** [comment]
有人没

**Comment by dileep8014** [comment]
same issue here

**Comment by Tyrone-web** [comment]
same issue here

**Comment by platform-fe** [comment]
same issue

**Comment by wanghongcheng0302** [comment]
same issue

**Comment by vagusX** [comment]
please raise a issue on https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by WeslleyDeSouza** [comment]
Workaround:
https://github.com/less/less.js/issues/3537

**Comment by qiaer** [comment]
+1
