### ISSUE TITLE
修正 npm 包名和项目名。

### ISSUE THREAD

**Issue by afc163** [ant-design/codemod-v4#28]
`codemod` 改为 `codemod-v4`

`@ant-design/codemod` 改为 `@ant-design/codemod-v4`。

因为已经有一个 https://github.com/ant-design/antd-codemod 了，写清楚会比较好区分。

**Comment by vagusX** [comment]
好

**Comment by vagusX** [comment]
bin 名也要改吗？antd-codemod-v4？有点长

**Comment by vagusX** [comment]
那 bin 就叫做 antd4-codemod 好了
