### ISSUE TITLE
cross-circle-o codemod 升级失败

### ISSUE THREAD

**Issue by vagusX** [ant-design/codemod-v4#31]
升级 antd-pro 过程中，出现该图标没有被迁移成功，需要排查原因

```jsx
<Icon type="cross-circle-o" className={styles.errorIcon} />
```

https://github.com/ant-design/ant-design-pro/blob/af29a840a969a38fddb91c9deb479a90b3c36c85/src/pages/form/advanced-form/index.tsx#L85

**Comment by vagusX** [comment]
![image](https://user-images.githubusercontent.com/6828924/70371327-8b901900-190c-11ea-8227-b48db1a9745f.png)

antd 官网没有 cross 这个图标，目前是按照 close 转的, 但是 cross-circle 并不会被转换

**Comment by vagusX** [comment]
试了一下 demo

https://stackblitz.com/edit/react-pm1kmr?embed=1&file=index.js

貌似这个是一个不存在图标？

**Comment by zombieJ** [comment]
看来是没有的，console warning 如何？

**Comment by vagusX** [comment]
codemod 迁移过程中的 warning 有点看不出来效果的，因为文件流太多了

**Comment by vagusX** [comment]
处理措施

* 通过 LegacyIcon 兼容处理，并在 LegacyIcon 中增加 warning 提示
* codemod 考虑以 summary 形式将这条信息写入，并在结束时输入 summary 到终端 stdout
