### ISSUE TITLE
better summary format

### ISSUE THREAD

**Issue by vagusX** [ant-design/codemod-v4#34]
![image](https://user-images.githubusercontent.com/6828924/70389820-9ecfe100-19ff-11ea-8cf9-b67bfbd4b7e1.png)

The table view cannot fit well in narrow screen

**Comment by zombieJ** [comment]
> 1. xxxx using invalidate xxx with legacy icon. (~/xxx/xxx/xxx.tsx - 233:44)
> 2. ...

**Comment by vagusX** [comment]
The line number is not reliable because it would change after transforming. @zombieJ

**Comment by vagusX** [comment]
`xxxx using invalidate xxx with legacy icon. (~/xxx/xxx/xxx.tsx - <SourCode />)`

**Comment by zombieJ** [comment]
```bash
file: /xxxx/xxxx/xxxx.tsx - line 16
>>> <Icon type="not-exist" />
xxxx using invalidate xxx with legacy icon.
```

**Comment by vagusX** [comment]
![image](https://user-images.githubusercontent.com/6828924/70788340-a8749280-1dcb-11ea-8f02-e839bb4c66bd.png)
