### ISSUE TITLE
升级执行命令之后一直提示命令行太长

### ISSUE THREAD

**Issue by jin-benben** [ant-design/codemod-v4#43]
![image](https://user-images.githubusercontent.com/27982466/71789575-cfd71c00-3066-11ea-98d6-4d96344a531a.png)

**Comment by sdhr27** [comment]
我也遇到了一样的问题，一直提示：Command failed with ENAMETOOLONG
只有tsx文件可以正常替换，所有js文件都失败了。

**Comment by vagusX** [comment]
初步推测是由于文件比较多，导致在 spawn 执行时命令行参数超长

**Comment by jin-benben** [comment]
> 初步推测是由于文件比较多，导致在 spawn 执行时命令行参数超长

那该如何解决，要把文件都分开，然后再执行升级吗

**Comment by vagusX** [comment]
我这边调整下这个地方的参数，然后争取今天发个版本解决下这个问题，请耐心等待下

**Comment by jin-benben** [comment]
> 我这边调整下这个地方的参数，然后争取今天发个版本解决下这个问题，请耐心等待下

好的，辛苦了

**Comment by vagusX** [comment]
@jin-benben 试试看 @ant-design/codemod-v4@1.0.0-alpha.7

**Comment by jin-benben** [comment]
> @jin-benben 试试看 @ant-design/codemod-v4@1.0.0-alpha.8

已经成功替换Form引用，但是会提示这个包找不到，是不是我还要另外安装这个包，现在项目antd 的版本是3.26.6

![image](https://user-images.githubusercontent.com/27982466/71877771-f5e2e600-3164-11ea-98e0-9da82cfa660c.png)

**Comment by vagusX** [comment]
> 个包找不到，是不是我还要另外安装这个包，现在项目antd 的版本是3.26.6

是的，这个包需要手动安装一下哈， 也需要手动安装下
* @ant-design/icons@4.0.0-alpha.19 # v4 版本
* @ant-design/compatible
