### ISSUE TITLE
项目采用的是svn，执行antd4-codemod src命令显示git还有未提交内容

### ISSUE THREAD

**Issue by hejinhua** [ant-design/codemod-v4#44]
![image](https://user-images.githubusercontent.com/39826101/71874564-32aadf00-315d-11ea-8da7-4cfcebaeb167.png)

**Comment by vagusX** [comment]
好的，这里需要加个选项，供跳过 git 检查用

**Comment by vagusX** [comment]
`antd4-codemod ts_fixtures --force` 尝试加一个 --force 选项来跳过 git 操作，但是还是一个危险操作，请先保障本地代码已提交，工作区无内容, 试试看 @ant-design/codemod-v4@1.0.0-alpha.8
