### ISSUE TITLE
升级之后对应icon找不到报错

### ISSUE THREAD

**Issue by hejinhua** [ant-design/codemod-v4#47]
![image](https://user-images.githubusercontent.com/39826101/71945441-cdf59000-3201-11ea-8439-c9c5e6105e38.png)

需自己手动修改为:
```javascript
import { Icon } from '@ant-design/compatible'
<Icon type='user' />
```

**Comment by vagusX** [comment]
请安装 @ant-design/icons 包

**Comment by hejinhua** [comment]
好吧，sorry，我以为用升级工具会自动安装这个包

**Comment by afc163** [comment]
@vagusX 升级文档和命令行输出中都提示一下吧。
