### ISSUE TITLE
关于Icon

### ISSUE THREAD

**Issue by phoema** [ant-design/codemod-v4#54]
你好，Icon为什么没有转换成文档里说的那种啊？
import Icon, { CodeFilled, SmileOutlined, SmileTwoTone } from '@ant-design/icons';

![image](https://user-images.githubusercontent.com/8730272/72807930-67598300-3c93-11ea-8bef-d4c937ec05fa.png)
确变成了这种形式
import { Form, Icon as LegacyIcon } from '@ant-design/compatible';
<LegacyIcon type="plus"/>
<LegacyIcon type="edit"/>

**Comment by phoema** [comment]
另外，提示了无数这些信息，我确认过了，plus等类似icon都是存在的
file: src\pages\fee\feestatement\component\FeeStatementList.jsx - 23:58
>>> icon="plus"
Contains an invalid icon, please check it at https://ant.design/components/icon

**Comment by vagusX** [comment]
还麻烦提供你在使用的 cli 的版本信息以及一个最小的可复现的代码仓库或者片段

**Comment by duskmoon314** [comment]
同样有这种情况，所有的 Icon 都改成了 @ant-design/compatible 中的 LegacyIcon。
查看之前的issue，尝试手动 `yarn add @ant-design/icons`后再执行npx那个指令，还是如此。

环境 win10，vscode，cmd终端，仓库为[eesast/web](https://github.com/eesast/web)

**Comment by aiyudeleng** [comment]
> 同样有这种情况，所有的 Icon 都改成了 @ant-design/compatible 中的 LegacyIcon。
> 查看之前的issue，尝试手动 `yarn add @ant-design/icons`后再执行npx那个指令，还是如此。
> 
> 环境 win10，vscode，cmd终端和Git Bash都试过了，仓库为[eesast/web](https://github.com/eesast/web)
> 
> 涉及到的图案有user、plus这些，在[https://ant.design/components/icon/中都有对应的xxxOutlined，理应和文档中所写的一样进行修改才对吧](https://ant.design/components/icon/%E4%B8%AD%E9%83%BD%E6%9C%89%E5%AF%B9%E5%BA%94%E7%9A%84xxxOutlined%EF%BC%8C%E7%90%86%E5%BA%94%E5%92%8C%E6%96%87%E6%A1%A3%E4%B8%AD%E6%89%80%E5%86%99%E7%9A%84%E4%B8%80%E6%A0%B7%E8%BF%9B%E8%A1%8C%E4%BF%AE%E6%94%B9%E6%89%8D%E5%AF%B9%E5%90%A7)

你好，你是怎么解决的？我这也是大量icon出问题

**Comment by phoema** [comment]
long time a go
