### ISSUE TITLE
Doesn't work on meteor project

### ISSUE THREAD

**Issue by erixtekila** [ant-design/codemod-v4#55]
The workers cycle accross the paths, see the react components with antd inside, but skip all of them.

**Comment by vagusX** [comment]
please provide the cli version info

**Comment by erixtekila** [comment]
`
antd4-codemod
Latest version is 1.0.0-alpha.14. Please update firstly
`

**Comment by vagusX** [comment]
> `antd4-codemod Latest version is 1.0.0-alpha.14. Please update firstly`

Please try the latest cli.

And could you please give me a simplest sample project

**Comment by erixtekila** [comment]
I close the issue because :

- on a fresh meteor + antd project the CLI works
- on an old one, not

BTW, the CLI miss a verbose flag and some exclude path options.
Best luck
