### ISSUE TITLE
Getting ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by maitysubhasis** [ant-design/codemod-v4#59]
On running command
```
$ antd4-codemod app
```

I am getting 
```
regeneratorRuntime.mark(function _callee2(input, options) {
^
ReferenceError: regeneratorRuntime is not defined
```
A quick search shows it might be babel config issue.

**Comment by vagusX** [comment]
@maitysubhasis you can try `@ant-design/codemod-v4@1.0.0-alpha.17`

**Comment by scottfuller4** [comment]
Also having this issue, and getting `Latest version is 1.0.0-alpha.19. Please update firstly` when trying to use `@ant-design/codemod-v4@1.0.0-alpha.17`

**Comment by FoxxMD** [comment]
Also having this issue. Cannot upgrade to alpha17 or 19 becuase of this error:
```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade yo
ur dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...O2uhVKZ8BJWhLkL3Etvrl'
```

**Comment by vagusX** [comment]
> Also having this issue, and getting `Latest version is 1.0.0-alpha.19. Please update firstly` when trying to use `@ant-design/codemod-v4@1.0.0-alpha.17`

Please upgrade to the latest version firstly

**Comment by vagusX** [comment]
> Also having this issue. Cannot upgrade to alpha17 or 19 becuase of this error:
> 
> 
> ```
> npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade yo
> ur dependencies to the actual version of core-js@3.
> npm ERR! Unexpected end of JSON input while parsing near '...O2uhVKZ8BJWhLkL3Etvrl'
> ```

You can try `yarn` instead?

**Comment by FoxxMD** [comment]
I did initially use yarn because npm was failing to install.  `npm cache clean --force` worked so I could install through npm but I am still experiencing these errors:

```
ReferenceError: regeneratorRuntime is not defined
    at _markDependency (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\transforms\utils\marker.js:60:53)
    at markDependency (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\transforms\utils\marker.js:56:26)
    at NodePath.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\transforms/v3-Component-to-compatible.js:58:9)
    at __paths.forEach (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\jscodeshift\src\Collection.js:75:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\jscodeshift\src\Collection.js:74:18)
    at importDeprecatedComponent (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\transforms/v3-Component-to-compatible.js:31:8)
    at module.exports (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\transforms/v3-Component-to-compatible.js:67:16)
```
```
ReferenceError: regeneratorRuntime is not defined
    at C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\dir-glob/index.js:44:1
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\dir-glob/index.js:44:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._compile (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
C:\Users\user\AppData\Roaming\nvm\v10.16.3\node_modules\@ant-design\codemod-v4\node_modules\dir-glob\index.js:65
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee2(input, options) {
```

**Comment by scottfuller4** [comment]
> > Also having this issue, and getting `Latest version is 1.0.0-alpha.19. Please update firstly` when trying to use `@ant-design/codemod-v4@1.0.0-alpha.17`
> 
> Please upgrade to the latest version firstly

But the regeneratorRuntime error is happening on `alpha.19`

**Comment by FoxxMD** [comment]
@scottfuller4 newest first is [v1.0.1](https://github.com/ant-design/codemod-v4/releases/tag/v1.0.1)

**Comment by vagusX** [comment]
dir-glob is the dependency of globby, maybe I need to replace this dependencies with other lib

**Comment by CyfforPro** [comment]
same issue happened at v1.0.1
```
ReferenceError: regeneratorRuntime is not defined
    at _markDependency (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms\utils\marker.js:60:53)
    at markDependency (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms\utils\marker.js:56:26)
    at C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms/v3-typings-to-compatible.js:61:11
    at NodePath.<anonymous> (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms/v3-typings-to-compatible.js:38:11)
    at C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\node_modules\jscodeshift\src\Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\node_modules\jscodeshift\src\Collection.js:74:18)
    at importDeprecatedTypings (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms/v3-typings-to-compatible.js:31:29)
    at module.exports (C:\Program\nodejs\node_cache\_npx\7932\node_modules\@ant-design\codemod-v4\transforms/v3-typings-to-compatible.js:73:16)
```

**Comment by vagusX** [comment]
you can try `@ant-design/codemod-v4@1.0.2`

**Comment by CyfforPro** [comment]
> you can try `@ant-design/codemod-v4@1.0.2` @maitysubhasis @CyfforPro @scottfuller4 @FoxxMD

sadly to say that the latest version(1.0.2) has the same 'regeneratorRuntime is not defined' error,
but it seems works better than v1.0.1--
v1.0.1: only modified my code on LocaleProvider, not work on all Icon and Form
v1.0.2: works on Icon at partial files

the error call stack is the same as I mentioned above

running environment:
node: v12.16.1
os: win10 1909

**Comment by FoxxMD** [comment]
Same results as Cyffor. node 10.16.3 on win10 18362 and macOS 10.14.6

**Comment by vagusX** [comment]
I must figure it out which module contains `regeneratorRuntime` 😂

**Comment by vagusX** [comment]
install all dependencies(without devDependencies), find the `@babel/runtime` depends on `regenerator-runtime`

![image](https://user-images.githubusercontent.com/6828924/76479424-aeb7f080-6446-11ea-9dc4-2695ed87af2d.png)

![image](https://user-images.githubusercontent.com/6828924/76479775-dcea0000-6447-11ea-822e-16814f60536d.png)

![image](https://user-images.githubusercontent.com/6828924/76479849-10c52580-6448-11ea-998f-a25d8a733492.png)

![image](https://user-images.githubusercontent.com/6828924/76479867-233f5f00-6448-11ea-891d-9d32f8bc1453.png)

```
regenerator-runtime --> regenerator-transform --> babel-plugin-transform-regenerator --> @babel/preset-env --> jscodeshift


@babel/runtime --> regenerator-transform --> babel-plugin-transform-regenerator --> @babel/preset-env --> jscodeshift
```

**Comment by vagusX** [comment]
> > you can try `@ant-design/codemod-v4@1.0.2` @maitysubhasis @CyfforPro @scottfuller4 @FoxxMD
> 
> sadly to say that the latest version(1.0.2) has the same 'regeneratorRuntime is not defined' error,
> but it seems works better than v1.0.1--
> v1.0.1: only modified my code on LocaleProvider, not work on all Icon and Form
> v1.0.2: works on Icon at partial files
> 
> the error call stack is the same as I mentioned above
> 
> running environment:
> node: v12.16.1
> os: win10 1909

You use yarn、npm or npx ?

**Comment by CyfforPro** [comment]
> > > you can try `@ant-design/codemod-v4@1.0.2` @maitysubhasis @CyfforPro @scottfuller4 @FoxxMD
> > 
> > 
> > sadly to say that the latest version(1.0.2) has the same 'regeneratorRuntime is not defined' error,
> > but it seems works better than v1.0.1--
> > v1.0.1: only modified my code on LocaleProvider, not work on all Icon and Form
> > v1.0.2: works on Icon at partial files
> > the error call stack is the same as I mentioned above
> > running environment:
> > node: v12.16.1
> > os: win10 1909
> 
> You use yarn, npm or npx ?

1.0.1, I used npx
1.0.2, I used npm...

**Comment by FoxxMD** [comment]
@vagusX I was able to get codemod working by

* cloning this repository locally (master)
* installing deps (npm)
* running `node bin/antd-codemod.js ../my/app/dir`

**Comment by vagusX** [comment]
> @vagusX I was able to get codemod working by
> 
> * cloning this repository locally (master)
> * installing deps (npm)
> * running `node bin/antd-codemod.js ../my/app/dir`

OMG, still cannot found the reason why `regeneratorRuntime is not defined`

**Comment by HsunTsai** [comment]
In Antd official website,
Antd recommend "npm i -g @ant-design/codemod-v4".
But your npm global does not have "regeneratorRuntime"

So~ do not use globle npm install !
Just install codemod-v4 in yout project and run.
(1) Go to your project
(2) npm i @ant-design/codemod-v4
(3) in package.json script add "antdV3toV4: antd4-codemod src"
(4) in terminal run "npm run antdV3toV4"

**Comment by vagusX** [comment]
I cannot reproduce this issue myself yet 😭

**Comment by CyfforPro** [comment]
> I cannot reproduce this issue myself yet 😭

I took a few hours to figure out the minimum not-working env, then I found that this issue is probably caused by babel-config——once a babel.config.js exist in the root, this issue happened.

I packed the reproduction-env blow, you can try it yourself

[reproduction.zip](https://github.com/ant-design/codemod-v4/files/4348140/reproduction.zip)

**Comment by vagusX** [comment]
> > I cannot reproduce this issue myself yet 😭
> 
> I took a few hours to figure out the minimum not-working env, then I found that this issue is probably caused by babel-config——once a babel.config.js exist in the root, this issue happened.
> 
> I packed the reproduction-env blow, you can try it yourself
> [reproduction.zip](https://github.com/ant-design/codemod-v4/files/4348168/reproduction.zip)

Thanks very much for your sample project. You can try `@ant-design/codemod-v4@1.1.0` now

**Comment by CyfforPro** [comment]
> > > I cannot reproduce this issue myself yet 😭
> > 
> > 
> > I took a few hours to figure out the minimum not-working env, then I found that this issue is probably caused by babel-config——once a babel.config.js exist in the root, this issue happened.
> > I packed the reproduction-env blow, you can try it yourself
> > [reproduction.zip](https://github.com/ant-design/codemod-v4/files/4348168/reproduction.zip)
> 
> Thanks very much for your sample project. You can try `@ant-design/codemod-v4@1.1.0` now

Forgot to say, this version works fine, good job! I think this issue can be closed.
