### ISSUE TITLE
codemod for FormComponentProps

### ISSUE THREAD

**Issue by vagusX** [ant-design/codemod-v4#63]
```ts
import { FormComponentProps } from 'antd/es/form';

import { FormComponentProps } from '@ant-design/compatible/es/form'; 
```

**Comment by afc163** [comment]
`import { FormComponentProps } from 'antd/es/form';`

这句话本身在 4.0 里也工作的，注意不要把用户给 4.0 写的代码给替换掉。

**Comment by vagusX** [comment]
> `import { FormComponentProps } from 'antd/es/form';`
> 
> 这句话本身在 4.0 里也工作的，注意不要把用户给 4.0 写的代码给替换掉。

好难

**Comment by zombieJ** [comment]
`FormComponentProps` 是为 `Form.create` 使用的，v4 不依赖他，应该是可以放心替换掉。

**Comment by vagusX** [comment]
> `FormComponentProps` 是为 `Form.create` 使用的，v4 不依赖他，应该是可以放心替换掉。

好棒

**Comment by vagusX** [comment]
@ant-design/codemod-v4@1.0.0-alpha.18
