### ISSUE TITLE
UnhandledPromiseRejectionWarning: 

### ISSUE THREAD

**Issue by andriyklym** [ant-design/codemod-v4#64]
I tried to run codemod for updating to antdV4 and gets the error 

![image](https://user-images.githubusercontent.com/22375996/75234418-42d95500-57c3-11ea-8cc9-ad414c30c701.png)

**Comment by andriyklym** [comment]
And yes, i cmd in admin mode

**Comment by vagusX** [comment]
maybe caused by `fs.walk` from dependency of `globby` 

![image](https://user-images.githubusercontent.com/6828924/75528881-47fe0480-5a4e-11ea-8a5a-bbdcedb424ba.png)

**Comment by vagusX** [comment]
you can try `@ant-design/codemod-v4@1.0.2` @andriyklym
