### ISSUE TITLE
Unexpected end of JSON input while parsing near '...nsform-modules-system

### ISSUE THREAD

**Issue by wangzongming** [ant-design/codemod-v4#67]
![image](https://user-images.githubusercontent.com/27466569/75520876-7de8bc00-5a41-11ea-8d4b-5e5bc8621ce8.png)
运行时候提示Latest version is 1.0.0-alpha.18. Please update firstly
然后就升级不上了

**Comment by vagusX** [comment]
能把下面那个 A complete log 的文件内容贴一下嘛？方便排查

**Comment by wangzongming** [comment]
我已经换了个方法弄好了，使用yarn安装就好了。
