### ISSUE TITLE
发布 1.0.0，增加包版本自检

### ISSUE THREAD

**Issue by afc163** [ant-design/codemod-v4#69]
- [ ] 1.0.0 正式版可以发了
- [ ] 运行前检查 `@ant-design/codemod-v4` 的版本，提示用户更新到最新版本再运行，避免运行了不完整的版本。

**Comment by vagusX** [comment]
> * [ ]  1.0.0 正式版可以发了
> * [ ]  运行前检查 `@ant-design/codemod-v4` 的版本，提示用户更新到最新版本再运行，避免运行了不完整的版本。

第二项是一直都有的，第一项明天法正式版本
