### ISSUE TITLE
antd 升级

### ISSUE THREAD

**Issue by kzabc** [ant-design/codemod-v4#70]
×
Unhandled Rejection (TypeError): antd_es_form__WEBPACK_IMPORTED_MODULE_5__.default.create(...) is not a function

**Comment by vagusX** [comment]
could you please take a capture for the terminal which just run codemod cli

**Comment by kzabc** [comment]
找到问题了是    
package.json中
+ "@ant-design/pro-table": "^2.0.1", 
-"@ant-design/pro-table": "^1.x.x",
