### ISSUE TITLE
Cannot find module '@ant-design/compatible'

### ISSUE THREAD

**Issue by helen123456** [ant-design/codemod-v4#74]
Cannot find module '@ant-design/compatible'

**Comment by helen123456** [comment]
按照官网的步骤从3.x升级4.x后，报了好多这个错，而且我看了node——module的@antd里都没有这个compatible包，尝试了好多遍了，请大佬解答下，到底哪里出了问题

**Comment by xuantinfx** [comment]
I have the issue

**Comment by xuantinfx** [comment]
After upgraded by execute `antd4-codemod src` you have seen that notification, please install or upgraded other libraries, It can fix your problem.
<img width="550" alt="Screen Shot 2020-03-02 at 5 40 09 PM" src="https://user-images.githubusercontent.com/34159561/75669226-43835700-5cad-11ea-88f3-05543cd5e1fe.png">

**Comment by gwuah** [comment]
@helen123456 Depending on your dependency manager, just run one of these in your console and restart your application. The errors should go away.

`yarn global add @ant-design/codemod-v4` or `npm install -g @ant-design/codemod-v4`

**Comment by vagusX** [comment]
> Cannot find module '@ant-design/compatible'

麻烦提供更多报错信息或者报错截屏

**Comment by vagusX** [comment]
> 底哪里出了问题
```bash
npm i @ant-design/compatible
```

@helen123456 把兼容包安装下？这个是迁移之后，部分不兼容需要通过兼容包去 work around

**Comment by helen123456** [comment]
今天重新尝试了一下，又爆出新的错误，

Cannot find module 'globby'
--
是怎么回事

**Comment by vagusX** [comment]
Please try to upgrade `@ant-design/codemod-v4@1.0.1`

**Comment by vagusX** [comment]
https://github.com/ant-design/codemod-v4/issues/83
