### ISSUE TITLE
升级后手机访问样式问题

### ISSUE THREAD

**Issue by kzabc** [ant-design/codemod-v4#78]
![2F26480E-C597-416F-80A3-236BFDD1FA79](https://user-images.githubusercontent.com/42925731/75701373-9d584100-5cee-11ea-913d-0d284c5e4aa9.png)
![18F0C434-7762-4411-84E8-9B2CC4AF99CB](https://user-images.githubusercontent.com/42925731/75701385-a3e6b880-5cee-11ea-875f-112085bb70c4.png)
以及轮播图不显示

**Comment by vagusX** [comment]
@kzabc Please report an issue to [ant design main repo](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
