### ISSUE TITLE
升级cli报错

### ISSUE THREAD

**Issue by pengxue-net** [ant-design/codemod-v4#79]
1、antd版本3.26.12，react版本16.12.0
2、执行 npx -p @ant-design/codemod-v4 antd4-codemod src
3、代码放在本地服务器上，已签入或脱机报同样错误，没有提示具体文件
Sorry that there are still some git changes
you must commit or stash them firstly

**Comment by godIsAProgrammer** [comment]
你要把本地修改过的文件先 commit 到 缓存区。

**Comment by afc163** [comment]
`Sorry that there are still some git changes,  you must commit or stash them firstly`

按提示操作。

**Comment by vagusX** [comment]
确保你本地的仓库 git 状态是 clear，也就是把你的代码 commit 下，或者 stash 掉

**Comment by pengxue-net** [comment]
> 确保你本地的仓库 git 状态是 clear，也就是把你的代码 commit 下，或者 stash 掉

我本地是装过git客户端，但是我当前这套代码是放在普通服务器上，通过visual studio 2019源代码管理器进行操作，执行升级脚本之前代码都签入，根本不是通过git存储库操作的

**Comment by pengxue-net** [comment]
> 确保你本地的仓库 git 状态是 clear，也就是把你的代码 commit 下，或者 stash 掉

我把git中代码全部stash看一下

**Comment by pengxue-net** [comment]
> 确保你本地的仓库 git 状态是 clear，也就是把你的代码 commit 下，或者 stash 掉

我这个问题和#80 那个问题是一样的
