### ISSUE TITLE
不使用git管理代码的项目使用报错

### ISSUE THREAD

**Issue by Immortalt** [ant-design/codemod-v4#80]
对于使用SVN管理代码的项目，项目中是没有.git文件夹的，也不需要和无法提交git。
但是运行
npm i -g @ant-design/codemod-v4
antd4-codemod src
还是被提醒了
Sorry that there are still some git changes
you must commit or stash them firstly
请问这个问题该怎么解决！急！

**Comment by Immortalt** [comment]
我要是有git changes没有提交，那我commit就是了。
可我没有用git，无法commit啊。。。

**Comment by vagusX** [comment]
`antd4-codemod src --force`

https://github.com/ant-design/codemod-v4/blob/master/bin/cli.js#L251

**Comment by pengxue-net** [comment]
antd4-codemod src --force 这个是好用的

**Comment by Immortalt** [comment]
antd4-codemod src --force 可行
建议在ant design的文档中优先指出，不然我估计还会有很多人遇到这个问题的。

**Comment by Yu-Rain** [comment]
项目中有未跟踪的文件也会报这个错误, 我把所有未跟踪文件删除了就可以了
