### ISSUE TITLE
Cannot find module 'globby'  

### ISSUE THREAD

**Issue by helen123456** [ant-design/codemod-v4#83]
今天重新尝试，爆Cannot find module 'globby'  出这个错，然后我就安装了"globby": "^3.0.0"，可是还是报这个错

**Comment by vagusX** [comment]
Please try to upgrade `@ant-design/codemod-v4@1.0.1`

**Comment by helen123456** [comment]
"@ant-design/codemod-v4": "^1.0.1"，已经更新了，=依旧报这个错

**Comment by vagusX** [comment]
麻烦方便的话 提供下报错截屏信息

**Comment by helen123456** [comment]
Time elapsed: 5.258seconds                                                                                                                                                   Transform v3-component-with-string-icon-props-to-v4                                                                                                                          Processing 263 files...                                                                                                                                                      Spawning 2 workers...                                                                                                                                                        Sending 50 files to free worker...                                                                                                                                           Sending 50 files to free worker...                                                                                                                                           internal/modules/cjs/loader.js:583                                                                                                                                               throw err;                                                                                                                                                                   ^                                                                                                                                                                                                                                                                                                                                                     Error: Cannot find module 'globby'                                                                                                                                               at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                                                  at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                                                             at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                    at require (internal/modules/cjs/helpers.js:22:18)
--

**Comment by helen123456** [comment]
`

Time elapsed: 5.258seconds                                                                                                                                                   Transform v3-component-with-string-icon-props-to-v4                                                                                                                          Processing 263 files...                                                                                                                                                      Spawning 2 workers...                                                                                                                                                        Sending 50 files to free worker...                                                                                                                                           Sending 50 files to free worker...                                                                                                                                           internal/modules/cjs/loader.js:583                                                                                                                                               throw err;                                                                                                                                                                   ^                                                                                                                                                                                                                                                                                                                                                     Error: Cannot find module 'globby'                                                                                                                                               at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                                                  at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                                                             at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                    at require (internal/modules/cjs/helpers.js:22:18)                                                                                                                           at Object. (C:\Users\17701\AppData\Roaming\npm\node_modules\@ant-                                                                                             design\codemod-v4\transforms\utils/icon.js:2:16)                                                                                                                                 at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                                                                   at Module._compile (C:\Users\17701\AppData\Roaming\npm\node_modules\@ant-des                                                                                             ign\codemod-v4\node_modules\pirates\lib\index.js:99:24)                                                                                                                          at Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                                                            at Object.newLoader [as .js] (C:\Users\17701\AppData\Roaming\npm\node_module                                                                                             s\@ant-design\codemod-v4\node_modules\pirates\lib\index.js:104:7)                                                                                                                at Module.load (internal/modules/cjs/loader.js:599:32)                                                                                                                   internal/modules/cjs/loader.js:583
--


`

**Comment by helen123456** [comment]
‘’‘

Time elapsed: 5.258seconds                                                                                                                                                   Transform v3-component-with-string-icon-props-to-v4                                                                                                                          Processing 263 files...                                                                                                                                                      Spawning 2 workers...                                                                                                                                                        Sending 50 files to free worker...                                                                                                                                           Sending 50 files to free worker...                                                                                                                                           internal/modules/cjs/loader.js:583                                                                                                                                               throw err;                                                                                                                                                                   ^                                                                                                                                                                                                                                                                                                                                                     Error: Cannot find module 'globby'                                                                                                                                               at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                                                  at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                                                             at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                    at require (internal/modules/cjs/helpers.js:22:18)
--



’‘’

**Comment by helen123456** [comment]
![image](https://user-images.githubusercontent.com/29134290/75747854-ff4d9080-5d58-11ea-9dbb-c256e72cb057.png)

**Comment by helen123456** [comment]
<img width="488" alt="1" src="https://user-images.githubusercontent.com/29134290/75747946-3cb21e00-5d59-11ea-9ffd-c67df0ac86e5.png">

**Comment by helen123456** [comment]
大神图片看的到吗

**Comment by vagusX** [comment]
@helen123456 能说下你的运行脚本是怎么安装的吗？看起来还是 1.0.0 版本报的错

**Comment by helen123456** [comment]
都好了，重新走了一遍，成功了，非常感谢
