### ISSUE TITLE
使用`codemod-v4`之前 是否得保证react 16.9^ ?

### ISSUE THREAD

**Issue by Chad97** [ant-design/codemod-v4#95]
- 使用`codemod-v4`之前 是否得保证react 16.9^ ?

**Comment by afc163** [comment]
对的，应该。

@vagusX 可以检查一下，react 版本，低于这个版本警告提示一下。

**Comment by Chad97** [comment]
- @afc163  升级完了 用的 16.13  项目说：“我好方～～” 
- 哈哈～

**Comment by gebilaoman** [comment]
用umi的脚手架创建出来的项目，react的版本还是低的
`
"react": "^16.8.6",
"react-dom": "^16.8.6",
`

**Comment by xianghongai** [comment]
![Sorry that there are still some git changes](https://user-images.githubusercontent.com/2075006/84123602-a20a5f00-aa6c-11ea-9dff-318332600bf9.png)

Sorry that there are still some git changes

you must commit or stash them firstly
