### ISSUE TITLE
升级到v4后，TypeError: _react.default.forwardRef is not a function

### ISSUE THREAD

**Issue by kiki000** [ant-design/codemod-v4#97]
![image](https://user-images.githubusercontent.com/29906548/76143408-2fc36080-60b2-11ea-9d49-fec2b9bc5caf.png)

react版本16.13.0

**Comment by vagusX** [comment]
你是ts项目吗？ tsconfig 是否开启了 esModuleInterop 选项？建议去 [ant design 主repo](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 提 issue

**Comment by kiki000** [comment]
不是ts
