### ISSUE TITLE
AutoComplete选中显示的为什么是value值而不是label值

### ISSUE THREAD

**Issue by helen123456** [ant-design/codemod-v4#98]
![image](https://user-images.githubusercontent.com/29134290/76157168-339dc400-6140-11ea-8e2a-6c4245c52cbf.png)

**Comment by vagusX** [comment]
Please report an issue to [ant design main repo](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)  @helen123456
